### ISSUE TITLE
Checkpoint #1

### ISSUE THREAD

**Issue by alexanderem49** [kralonur/solidity_erc20_realization#1]
EIP-20 violation, `function decimals() public view returns (uint8)` is required

https://github.com/kralonur/Solidity-ERC20-Realization/blob/f6d425fd35d246766f49d959c3f3474ff620d5ab/contracts/ERC20Token.sol#L12

**Comment by kralonur** [comment]
https://github.com/kralonur/Solidity-ERC20-Realization/blob/225bbbc674bdf9c3e9ec19d30d7055d75e262744/contracts/ERC20Token.sol#L152-L155
solved
